Entities/Fan.cs
using System.ComponentModel.DataAnnotations;

public class Fan
{
    [Key]
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Discription { get; set; }
    public List<UserFan> FanUsers { get; set; }
    public Guid SchoolId { get; set; }
    public School School { get; set; }
    public List<TaskEntity> Tasks { get; set; }
}

Controllers/FanController.cs
using System.Net;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Classrom.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;
using C.Services;
using ClassRoom.Data.DbContext;
using Microsoft.EntityFrameworkCore;

namespace Classrom.Controllers;

[Authorize]
public class FanController : Controller
{
    private readonly AppDbContext context;
    private readonly GetUserId _userid;

    public FanController(AppDbContext context, GetUserId userid)
    {
        this.context = context;
        _userid = userid;
    }

    public async Task<IActionResult> AddFan(Guid schoolid)
    {
        ViewBag.SchoolId = schoolid;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddFan(Guid schoolid, [FromForm] FanDto dto)
    {
        if(!ModelState.IsValid)
        {
            return View(dto);
        }
        var fans = await context.Fans.Where(p=>p.SchoolId == schoolid).ToListAsync();

        if(fans.Any(p=>p.Name == dto.Name))
        {
            ModelState.AddModelError("Name", "this scince already have in this school");
            return View();
        }

        var fan = new Fan()
        {
            Name = dto.Name,
            Discription = dto.Description,
            SchoolId = schoolid
        };
        var userid = _userid.UserId;
        fan.FanUsers = new List<UserFan>()
        {
            new UserFan()
            {
                UserId = userid,
                Type = EUserFan.Teacher
            }
        };
        var school = await context.SchoolSet.Include(p=>p.Fans).FirstOrDefaultAsync(p=>p.Id == schoolid);
        school.Fans.Add(fan);
        context.Fans.Add(fan);
        await context.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }

    public async Task<IActionResult> View(Guid id)
    {
        var fan = await context.Fans.Include(p=>p.FanUsers).ThenInclude(p=>p.User).FirstOrDefaultAsync(p=>p.Id == id);
        return View(fan);
    }
    [HttpGet]
    public async Task<IActionResult> Share(Guid fanid)
    {
        ViewBag.FanId = fanid;
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Share(Guid fanid, [FromForm] TaklifnomaDto join)
    {
        var userid = _userid.UserId;
        var touser = await context.Users.FirstOrDefaultAsync(p=>p.UserName == join.UserName);

        var IsJoined = await context.Requests.AnyAsync(p=>p.ToUserId == touser.Id && p.FanId == fanid);
        var IsAgainJoined = await context.UsersFans.AnyAsync(p=>p.UserId == touser.Id && p.FanId == fanid);

        if(IsJoined || IsAgainJoined)
        {
            return RedirectToAction("View", new {id = fanid});
        }

        var jn = new Taklifnoma()
        {
            FanId = fanid,
            ToUserId = touser.Id,
            FromUserId = userid,
            IsJoined = false
        };
        context.Requests.Add(jn);
        await context.SaveChangesAsync();
        return RedirectToAction("View", new {id = fanid});
    }

    public async Task<IActionResult> JoinR(Guid reqid, bool j)
    {
        var join = await context.Requests.FirstOrDefaultAsync(p=>p.Id == reqid);
        if(j)
        {
            var taklif = new UserFan()
            {
                FanId = join.FanId,
                UserId = join.ToUserId,
                Type = EUserFan.Student
            };
            join.IsJoined = true;
            context.UsersFans.Add(taklif);
        }
        else
        {
            context.Requests.Remove(join);
        }
        await context.SaveChangesAsync();
        return RedirectToAction("Profile", "User");
    }

    public async Task<IActionResult> SearchFan(string name)
    {
        //if(name == null) return RedirectToAction("View");
        if(context.Fans.Any(p=>p.Name.Contains(name)))
        {
            var sch = await context.Fans.Where(p=>p.Name.Contains(name)).Include(p=>p.FanUsers).ToListAsync();
            return View(sch);
        }
        return RedirectToAction("NotFound");
    }

    public async Task<IActionResult> NotFound()
    {
        return View();
    }
}

Views/Fan/AddFan.cshtml
@model FanDto

<h1 style="margin: auto; text-align: center">Create Scince</h1>
<form class="row g-3" style="width: 400px; margin: auto" asp-controller="Fan" asp-action="AddFan" asp-route-schoolid="@ViewBag.SchoolId" enctype="multipart/form-data" method="post">
    <div>
        <input name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name" required/>
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <input name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description" required/>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <button class="form-control btn btn-success" type="submit">Create</button>
    <a class="link-info" asp-controller="Home" asp-action="Index">Back</a>
</form>

Views/Fan/Index.cshtml
@using Microsoft.EntityFrameworkCore;

@using ClassRoom.Data.DbContext
@model School
@inject AppDbContext context
@{
    var fans = await context.Fans.Where(p=>p.SchoolId == Model.Id).Include(p=>p.FanUsers).ThenInclude(p=>p.User).ToListAsync();
}
<h1 style="text-align: center;">Fanlar</h1>
<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Users</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < fans.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <th>@(fans[i].Name)</th>
                <th>@(fans[i].Discription)</th>
                <th>@(fans[i].FanUsers.Count)</th>
                <th><a type="button" asp-controller="Fan" asp-action="View" asp-route-id="@fans[i].Id">View</a></th>
            </tr>
        }
    </tbody>
</table>

Views/Fan/NotFound.cshtml
<h1 style="text-align: center">Not found sorry</h1>

Views/Fan/SearchFan.cshtml
@model List<Fan>
<div class="row">
    <h1 style="text-align: center;">Results</h1>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid" style="float: right;">
        <form class="d-flex" role="search" asp-controller="Fan" asp-action="SearchFan">
          <input name="name" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
</div>
<a asp-controller="School;" asp-action="Index">Back</a>
<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Users</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <th>@(Model[i].Name)</th>
                <th>@(Model[i].Discription)</th>
                <th>@(Model[i].FanUsers.Count)</th>
                <th><a class="btn btn-primary" type="button" asp-controller="Fan" asp-action="View" asp-route-id="@Model[i].Id">View</a></th>
            </tr>
        }
    </tbody>
</table>

Views/Fan/Share.cshtml
@model TaklifnomaDto

<h1 style="margin: auto; text-align: center">Share</h1>
<form class="row g-3" style="width: 400px; margin: auto" asp-controller="Fan" asp-action="Share" asp-route-fanid="@ViewBag.FanId" method="post">
    <div>
        <input name="UserName" class="form-control" asp-for="UserName" type="text" placeholder="UserName" required/>
        <span class="text-danger" asp-validation-for="UserName"></span>
    </div>
    <button class="form-control btn btn-success" type="submit">Send request</button>
</form>

Views/Fan/View.cshtml
@using C.Services;
@model Fan
@inject GetUserId id
<div style="display: flex; width: 100%; background-color: black; border-radius: 50px;">
    <div style="margin: 10% 2%;">
        <h1 style="color: green;">Fan : @Model.Name</h1>
        <h2 style="color: green;">Description : @Model.Discription</h2>
        <h3 style="color: green;">Teacher : @Model.FanUsers.FirstOrDefault(p=>p.Type == EUserFan.Teacher)!.User.FirstName</h3>
        @{
            var userid = id.UserId;
            @* if(!Model.FanUsers.Any(p=>p.UserId == userid)) *@
            @* { *@
                @* <a class="btn btn-info" type="submit" asp-controller="School" asp-action="Join" asp-route-id="@Model.Id">Join to school</a> *@
            @* } *@
            if(Model.FanUsers.Any(p=>p.UserId == userid))
            {
                var n = Model.FanUsers.FirstOrDefault(p=>p.UserId == userid);
                if(n.Type == EUserFan.Teacher)
                {
                    <a class="btn btn-success" type="submit" asp-controller="Fan" asp-action="Share" asp-route-fanid="@Model.Id">to share</a>
                    <a class="btn btn-success" type="submit" asp-controller="Task" asp-action="Index" asp-route-id="@Model.Id">Tasks</a>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="mdo">Add Task</button>
                    @* <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@fat">Open modal for @fat</button> *@
                    @* <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Open modal for @getbootstrap</button> *@
                    
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">New message</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <form>
                              <div class="mb-3">
                                <label for="recipient-name" class="col-form-label">Recipient:</label>
                                <input type="text" class="form-control" id="recipient-name">
                              </div>
                              <div class="mb-3">
                                <label for="message-text" class="col-form-label">Message:</label>
                                <textarea class="form-control" id="message-text"></textarea>
                              </div>
                            </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <a type="button" class="btn btn-primary" asp-controller="Task" asp-action="AddTask" asp-route-id="@Model.Id">Send message</a>
                          </div>
                        </div>
                      </div>
                    </div>
                }
            }
        }
    </div>
    <div style="margin: 5%; margin-left: 40%;">
        <img src="@Model.FanUsers.FirstOrDefault(p=>p.UserId == Model.FanUsers.FirstOrDefault(p=>p.Type == EUserFan.Teacher)!.User.Id).User.PhotoUrl" alt="" style="width: 350px; height: 350px; border-radius: 50%; margin-top: 2%; padding: 2%">
    </div>

</div>

<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Logo</th>
            <th scope="col">Name</th>
            <th scope="col">UserName</th>
            <th scope="col">Phone</th>
            <th scope="col">Role</th>
            <th scope="col">Nb</th>
        </tr>
    </thead>
    <tbody>
        @{
        for (int i = 0; i < Model.FanUsers.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <td><img src="@(Model.FanUsers[i].User.PhotoUrl)" alt="" style="width: 20px; height: 20px;"></td>
                <td>@(Model.FanUsers[i].User.FirstName) @(Model.FanUsers[i].User.LastName)</td>
                <td>@(Model.FanUsers[i].User.UserName)</td>
                <td>@(Model.FanUsers[i].User.PhoneNumber)</td>
                <td>@(Model.FanUsers[i].Type)</td>
                <td>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    </div>
                </td>
            </tr>
        }}
    </tbody>
</table>