Entities/School.cs
using System.ComponentModel.DataAnnotations;

public class School
{
    [Key]
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string PhotoUrl { get; set; }
    public List<UserSchool> Users {get; set;}
    public List<Fan> Fans { get; set; }

}

Controllers/SchoolController.cs
using System.Net;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Classrom.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;
using C.Services;
using ClassRoom.Data.DbContext;
using Microsoft.EntityFrameworkCore;

namespace Classrom.Controllers;

[Authorize]
public class SchoolController : Controller
{
    private readonly AppDbContext context;
    private readonly GetUserId _userid;

    public SchoolController(AppDbContext context, GetUserId userid)
    {
        this.context = context;
        _userid = userid;
    }

    public async Task<IActionResult> CreateSchool()
    {
        return View();
    }
 
    [HttpPost]
    public async Task<IActionResult> CreateSchool([FromForm] SchoolDto dto)
    {
        if(!ModelState.IsValid)
        {
            return View(dto);
        }

        var school = new School()
        {
            Name = dto.Name,
            Description = dto.Description,
            PhotoUrl = await SavePhoto.SaveSchoolsFile(dto.PhotoUrl)
        };

        var userid = _userid.UserId;

        school.Users = new List<UserSchool>()
        {
            new UserSchool()
            {
                UserId = userid,
                Type = EUserSchool.Creater
            }
        };

        context.SchoolSet.Add(school);
        await context.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Index(int page = 0, string query = "", bool sort = false)
    {
        ViewBag.Page = page;
        List<School> schools = default;
        if(sort)
        {
            //var queryr = from x in context.SchoolSet select x;
            switch (query)
            {
                case "Named" : schools = await context.SchoolSet.Include(p=>p.Users).OrderBy(x=>x.Name).ToListAsync(); break;
                case "MUsersCount" : schools = await context.SchoolSet.Include(p=>p.Users).OrderByDescending(x=>x.Users.Count).ToListAsync(); break;
                case "mUsersCount" : schools = await context.SchoolSet.Include(p=>p.Users).OrderBy(x=>x.Users.Count).ToListAsync(); break;
            }
            return View("Sorting", schools);
            //schools = context.SchoolSet.GroupBy(p=>p.Users).Select(p=>p.Count);
        }
        schools = await context.SchoolSet.Include(school=>school.Users).ThenInclude(o=>o.User).ToListAsync();
        return View(schools);
    }
    public async Task<IActionResult> Sorting()
    {
        return View();
    }

    public async Task<IActionResult> View(Guid id)
    {
        var school = await context.SchoolSet.Include(school=>school.Users).ThenInclude(userschool=>userschool.User).FirstOrDefaultAsync(p=>p.Id == id);
        return View(school);
    }

    public async Task<IActionResult> Join(Guid id)
    {
        var school = await context.SchoolSet.Include(s=>s.Users).ThenInclude(p=>p.User).FirstOrDefaultAsync(p=>p.Id == id);
        var userid = _userid.UserId;
        if(!school.Users.Any(p=>p.UserId == userid))
        {
            school.Users.Add(new UserSchool()
            {
                UserId = userid,
                Type = EUserSchool.Student
            });
        }
        await context.SaveChangesAsync();
        
        return RedirectToAction("View", new{id = school.Id}); 
    }

    [HttpGet]
    public async Task<IActionResult> UpdateSchool(Guid id)
    {
        var school = await context.SchoolSet.Include(s=>s.Users).ThenInclude(p=>p.User).FirstOrDefaultAsync(p=>p.Id == id);
        return View(new UpdateSchoolDto()
        {
            Name = school.Name,
            Description = school.Description
        });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateSchool(Guid id, [FromForm] UpdateSchoolDto dto)
    {
        var school = await context.SchoolSet.Include(s=>s.Users).ThenInclude(p=>p.User).FirstOrDefaultAsync(p=>p.Id == id);
        school.Description = dto.Description;
        school.Name = dto.Name;
        school.PhotoUrl = await SavePhoto.SaveSchoolsFile(dto.PhotoUrl);
        await context.SaveChangesAsync();
        return RedirectToAction("View", new {id = id});
    }
    public async Task<IActionResult> UpdateRole(Guid userid, Guid schoolid, EUserSchool role)
    {
        var school = await context.UserSchools.FirstOrDefaultAsync(p=>p.UserId == userid && p.SchoolId == schoolid);
        if(school.Type != EUserSchool.Creater || role != EUserSchool.Creater)
        {
            school.Type = role;
        }
        await context.SaveChangesAsync();
        return RedirectToAction("View", new {id = schoolid});
    }

    public async Task<IActionResult> Students(Guid id)
    {
        var students = context.SchoolSet.Where(p=>p.Id == id);
        return View(students);
    }

    public async Task<IActionResult> SearchSchool(string name)
    {
        if(name == null) return RedirectToAction("Index");
        if(context.SchoolSet.Any(p=>p.Name.Contains(name)))
        {
            var sch = await context.SchoolSet.Where(p=>p.Name.Contains(name)).Include(p=>p.Users).ToListAsync();
            return View(sch);
        }
        return RedirectToAction("NotFound");
    }

    public async Task<IActionResult> NotFound()
    {
        return View();
    }
}

Views/School/CreateSchool.cshtml
@model SchoolDto

<h1 style="margin: auto; text-align: center">Create School</h1>
<form class="row g-3" style="width: 400px; margin: auto" asp-controller="School" asp-action="CreateSchool" enctype="multipart/form-data" method="post">
    <div>
        <input name="PhotoUrl" class="form-control" asp-for="PhotoUrl" type="file" required/>
        <span class="text-danger" asp-validation-for="PhotoUrl"></span>
    </div>
    <div>
        <input name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name" required/>
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <input name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description" required/>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <button class="form-control btn btn-success" type="submit">Create School</button>
    <a class="link-info" asp-controller="Home" asp-action="Index">Back</a>
</form>

<button type="button" class="btn btn-primary" id="liveToastBtn">Show live toast</button>
  

Views/School/Index.cshtml
@model List<School>
<h1 style="text-align: center;">Schools</h1>
<div class="row" style="display: flex; margin-bottom: 5%;">
  <div class="container-fluid" style="width: 30%">
    <form class="d-flex" role="search" asp-controller="School" asp-action="SearchSchool">
      <input name="name" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
  <div class="btn-group dropend" style="width: 30%">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      Sorting
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="MUsersCount">MUsersCount</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="mUsersCount">mUsersCount</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="Named">Named</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="false">Random</a></li>
    </ul>
  </div>
  <a class="btn btn-warning" asp-controller="School" asp-action="CreateSchool" style="width: 30%">Create School</a>
</div>
@{
  var page = ViewBag.Page;
  var tugash = page * 6 + 6 <= Model.Count ? (page * 6 + 6) : Model.Count;
} 
          <div class="row row-cols-1 row-cols-md-3 g-4">
            @for (int i = page * 6; i < tugash; i++)
            {
              <div class="col">
                <div class="card" style="margin-top: 1%;">
                  <img src="@(Model[i].PhotoUrl)" class="card-img-top" alt="..." style="height: 50%">
                  <div class="card-body">
                    <h3 class="card-title" style="color: blue;"><strong>@(Model[i].Name)</strong></h3>
                    <p class="card-text" style="color: red;">Description : @(Model[i].Description)</p>
                    <h5 class="card-title" style="color: green;">Users : @(Model[i].Users.Count)</h5>
                  </div>
                  <a class="btn btn-primary" type="button" asp-controller="School" asp-action="View" asp-route-id="@Model[i].Id">View</a>
                </div>
              </div>
            }
          </div>

@{ bool juft = false; bool toq = false;
if(Model.Count>0)
{
  if(Model.Count % 2 == 0)
  {
    juft = true;
  }
  else
  {
    toq = true;
  }
      <nav class="d-flex justify-content-center" aria-label="Page navigation example" style="width: 60%; margin-top: 30px; margin-left: 20%; margin-right: 20%;">
        <ul class="pagination" style="">
            @if(page > 0)
            {
                <li class="page-item"><a class="page-link" asp-controller="School" 
                asp-action="Index" 
                asp-route-page="@(page-1)">Previous</a></li>
            }
            @if(juft)
            {
              @for (int i = 0; i < Model.Count/6; i++)
              {
                <li class="page-item"><a class="page-link" asp-controller="School" 
                asp-action="Index" 
                asp-route-page="@i">@(i+1)</a></li>
              }
              if(page < Model.Count/6-1)
              {
                <li class="page-item"><a class="page-link" asp-controller="School" 
                asp-action="Index" 
                asp-route-page="@(page+1)">Next</a></li>
              }         
            }
            @if(toq)
            {
              @for (int i = 0; i < Model.Count/6+1; i++)
              {
                  <li class="page-item"><a class="page-link" asp-controller="School" 
                  asp-action="Index" 
                  asp-route-page="@i">@(i+1)</a></li>
              }
              if(page < Model.Count/6)
              {
                  <li class="page-item"><a class="page-link" asp-controller="School" 
                  asp-action="Index" 
                  asp-route-page="@(page+1)">Next</a></li>
              }         
            }
           
        </ul>
    </nav>
}
}

Views/School/NotFound.cshtml
<h1 style="text-align: center">Not found sorry</h1>

Views/School/SearchSchool.cshtml
@model List<School>
<div class="row">
    <h1 style="text-align: center;">Schools result</h1>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid" style="float: right;">
        <form class="d-flex" role="search" asp-controller="School" asp-action="SearchSchool">
          <input name="name" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
</div>
<a asp-controller="School" asp-action="Index">Back</a>
<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Logo</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Users</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <th><img src="@(Model[i].PhotoUrl)" alt="" style="width: 30px; height: 30px; border-radius: 50%"></th>
                <th>@(Model[i].Name)</th>
                <th>@(Model[i].Description)</th>
                <th>@(Model[i].Users.Count)</th>
                <th><a class="btn btn-primary" type="button" asp-controller="School" asp-action="View" asp-route-id="@Model[i].Id">View</a></th>
            </tr>
        }
    </tbody>
</table>

Views/School/Sorting.cshtml
@model List<School>

<h1 style="text-align: center;">Results</h1>
<br>
  <div class="btn-group dropend" style="width: 30%; margin-bottom: 10px;">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      Sorting
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="MUsersCount">MUsersCount</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="mUsersCount">mUsersCount</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="true" asp-route-query="Named">Named</a></li>
      <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="Index" asp-route-sort="false">Random</a></li>
    </ul>
  </div>

  <br>
<a class="btn btn-danger" asp-controller="School" asp-action="Index">Back</a>
<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Users</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <th>@(Model[i].Name)</th>
                <th>@(Model[i].Description)</th>
                <th>@(Model[i].Users.Count)</th>
                <th><a type="button" asp-controller="School" asp-action="View" asp-route-id="@Model[i].Id">View</a></th>
            </tr>
        }
    </tbody>
</table>

Views/School/Students.cshtml
@model School

<table>
    <thead>
        <tr>№</tr>
        <td>Logo</td>
        <td>Name</td>
        <td>UserName</td>
        <td>Phone</td>
    </thead>
    <tbody>
        @{
            for (int i = 0; i < Model.Users.Count; i++)
            {
                <th>@(i+1)</th>
                <th><img src="@(Model.Users[i].User.PhotoUrl)" alt="" style="height: 30px; width: 30px;"></th>
                <th>@(Model.Users[i].User.FirstName) @(Model.Users[i].User.LastName)</th>
                <th>@(Model.Users[i].User.UserName)</th>
                <th>@(Model.Users[i].User.PhoneNumber)</th>
            }
        }
    </tbody>
</table>

Views/School/UpdateSchool.cshtml
@model UpdateSchoolDto

<h1 style="margin: auto; text-align: center">Create School</h1>
<form class="row g-3" style="width: 400px; margin: auto" asp-controller="School" asp-action="UpdateSchool" enctype="multipart/form-data" method="post">
    <div>
        <input name="PhotoUrl" class="form-control" asp-for="PhotoUrl" type="file" required/>
        <span class="text-danger" asp-validation-for="PhotoUrl"></span>
    </div>
    <div>
        <input name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name" required/>
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <input name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description" required/>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <button class="form-control btn btn-success" type="submit">Update School</button>
</form>

Views/School/View.cshtml
@using C.Services;
@model School
@inject GetUserId id
<div style="display: flex; width: 100%; background-color: black; border-radius: 50px;">
    <div style="margin: 10% 2%;">
        <h1 style="color: green;">School : @Model.Name</h1>
        <h2 style="color: green;">Description : @Model.Description</h2>
        <h3 style="color: green;">Creater : @Model.Users.FirstOrDefault(p=>p.Type == EUserSchool.Creater)!.User.FirstName</h3>
        @{
            var userid = id.UserId;
            if(!Model.Users.Any(p=>p.UserId == userid))
            {
                <a class="btn btn-info" type="submit" asp-controller="School" asp-action="Join" asp-route-id="@Model.Id">Join to school</a>
            }
            if(Model.Users.Any(p=>p.UserId == userid))
            {
                var n = Model.Users.FirstOrDefault(p=>p.UserId == userid);
                if(n.Type == EUserSchool.Creater)
                {
                    <a class="btn btn-success" type="submit" asp-controller="School" asp-action="UpdateSchool" asp-route-id="@Model.Id">Update</a>
                }
                if(n.Type == EUserSchool.Teacher)
                {
                    <a class="btn btn-success" type="submit" asp-controller="Fan" asp-action="AddFan" asp-route-schoolid="@Model.Id">Add Fan</a>
                }
            }
            <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Fanlar</button>

        }
    </div>
    <div style="margin: 5%; margin-left: 40%;">
        <img src="@Model.PhotoUrl" alt="" style="width: 350px; height: 350px; border-radius: 50%; margin-top: 2%">
    </div>

</div>

<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Logo</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Role</th>
        </tr>
    </thead>
    <tbody>
        @{ var user = Model.Users.FirstOrDefault(p=>p.UserId == id.UserId);
        for (int i = 0; i < Model.Users.Count; i++)
        {
            <tr>
                <th scope="col">@(i+1)</th>
                <td><img src="@(Model.Users[i].User.PhotoUrl)" alt="" style="width: 20px; height: 20px;"></td>
                <td>@(Model.Users[i].User.FirstName) @(Model.Users[i].User.LastName)</td>
                <td>@(Model.Users[i].User.PhoneNumber)</td>
                @{ 
                    if(user != null){
                    if(Model.Users[i].UserId != id.UserId && Model.Users[i].Type != EUserSchool.Creater && (user.Type == EUserSchool.Creater || user.Type == EUserSchool.Admin))
                    {
                    <td>
                        <div class="dropdown">
                          <a class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @(Model.Users[i].Type)
                          </a>
                          <ul class="dropdown-menu">
                            <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="UpdateRole" asp-route-userid="@Model.Users[i].UserId" asp-route-schoolid="@Model.Id" asp-route-role="@EUserSchool.Admin">Admin</a></li>
                            <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="UpdateRole" asp-route-userid="@Model.Users[i].UserId" asp-route-schoolid="@Model.Id" asp-route-role="@EUserSchool.Teacher">Teacher</a></li>
                            <li><a class="dropdown-item" type="button" asp-controller="School" asp-action="UpdateRole" asp-route-userid="@Model.Users[i].UserId" asp-route-schoolid="@Model.Id" asp-route-role="@EUserSchool.Student">Student</a></li>
                          </ul>
                        </div>
                    </td>
                    }
                    else
                    {
                        <td>@(Model.Users[i].Type)</td>
                    }}
                } 
            </tr>
        }}
    </tbody>
</table>


<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">@Model.Name</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="container-fluid">
      <form class="d-flex" role="search" asp-controller="Fan" asp-action="SearchFan">
        <input name="name" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <partial name="../Fan/Index.cshtml" />
  </div>
</div>